# See https://openmod.github.io/openmod-docs/devdoc/concepts/configuration.html
# You can delete this file if you do not need a configuration

wait: 5
damage: false
move: false
stance: PRONE
beds:
  - 288
  - 289
  - 290
  - 291
  - 292
  - 293
  - 294
  - 295